package enums_test

import (
	"testing"

	warehouseenum "github.com/Potato-Mart/Backend-Shared-Contract/v23/pkg/contracts/supply/warehouse"
)

func TestWarehouseEnumsValidateKnownValues(t *testing.T) {
	assertStringEnums(t, []enumCase{
		{name: "warehouseenum.PackingDamageHandling", valid: []stringEnum{warehouseenum.PackingDamageReplaceFromStock, warehouseenum.PackingDamageShortShipRefund}, invalid: warehouseenum.PackingDamageHandling("__invalid__")},
		{name: "warehouseenum.CameraProjection", valid: []stringEnum{warehouseenum.CameraPerspective, warehouseenum.CameraOrthographic}, invalid: warehouseenum.CameraProjection("__invalid__")},
		{name: "warehouseenum.DamageStage", valid: []stringEnum{warehouseenum.DamageStageInbound, warehouseenum.DamageStagePicking, warehouseenum.DamageStagePacking, warehouseenum.DamageStageStorage}, invalid: warehouseenum.DamageStage("__invalid__")},
		{name: "warehouseenum.InboundReceiptStatus", valid: []stringEnum{warehouseenum.InboundReceiptStatusDraft, warehouseenum.InboundReceiptStatusConfirmed}, invalid: warehouseenum.InboundReceiptStatus("__invalid__")},
		{name: "warehouseenum.LayoutNodeType", valid: []stringEnum{warehouseenum.LayoutNodeZone, warehouseenum.LayoutNodeAisle, warehouseenum.LayoutNodeRack, warehouseenum.LayoutNodeShelf, warehouseenum.LayoutNodeBin}, invalid: warehouseenum.LayoutNodeType("__invalid__")},
		{name: "warehouseenum.ModelFormat", valid: []stringEnum{warehouseenum.ModelFormatGLB, warehouseenum.ModelFormatGLTF, warehouseenum.ModelFormatOBJ, warehouseenum.ModelFormatFBX, warehouseenum.ModelFormatUSDZ}, invalid: warehouseenum.ModelFormat("__invalid__")},
		{name: "warehouseenum.OutboundShipmentStatus", valid: []stringEnum{warehouseenum.OutboundShipmentStatusPacked, warehouseenum.OutboundShipmentStatusDispatched, warehouseenum.OutboundShipmentStatusDelivered}, invalid: warehouseenum.OutboundShipmentStatus("__invalid__")},
		{name: "warehouseenum.PackingDiscrepancyKind", valid: []stringEnum{warehouseenum.PackingDiscrepancyKindShortage, warehouseenum.PackingDiscrepancyKindOverweight, warehouseenum.PackingDiscrepancyKindDamaged, warehouseenum.PackingDiscrepancyKindPending}, invalid: warehouseenum.PackingDiscrepancyKind("__invalid__")},
		{name: "warehouseenum.PickingItemStatus", valid: []stringEnum{warehouseenum.PickingItemStatusPending, warehouseenum.PickingItemStatusPartial, warehouseenum.PickingItemStatusComplete, warehouseenum.PickingItemStatusSkipped}, invalid: warehouseenum.PickingItemStatus("__invalid__")},
		{name: "warehouseenum.PickingListStatus", valid: []stringEnum{warehouseenum.PickingListStatusPending, warehouseenum.PickingListStatusInProgress, warehouseenum.PickingListStatusComplete, warehouseenum.PickingListStatusCancelled}, invalid: warehouseenum.PickingListStatus("__invalid__")},
		{name: "warehouseenum.ShapeType", valid: []stringEnum{warehouseenum.ShapeBox, warehouseenum.ShapeCylinder, warehouseenum.ShapeSphere, warehouseenum.ShapePlane, warehouseenum.ShapeCustom}, invalid: warehouseenum.ShapeType("__invalid__")},
		{name: "warehouseenum.StockMovementType", valid: []stringEnum{warehouseenum.StockMovementTypeReceipt, warehouseenum.StockMovementTypeTransfer, warehouseenum.StockMovementTypeStage, warehouseenum.StockMovementTypeUnstage, warehouseenum.StockMovementTypePackageConversion, warehouseenum.StockMovementTypeSaleCommit, warehouseenum.StockMovementTypeReturn, warehouseenum.StockMovementTypeQualityHold, warehouseenum.StockMovementTypeQualityRelease, warehouseenum.StockMovementTypeQualityReject, warehouseenum.StockMovementTypeAdjustment, warehouseenum.StockMovementTypeReturnToVendor, warehouseenum.StockMovementTypeScrap}, invalid: warehouseenum.StockMovementType("__invalid__")},
		{name: "warehouseenum.InventoryDateMarkKind", valid: []stringEnum{warehouseenum.InventoryDateMarkBestBefore, warehouseenum.InventoryDateMarkExpiry}, invalid: warehouseenum.InventoryDateMarkKind("__invalid__")},
		{name: "warehouseenum.InventoryCondition", valid: []stringEnum{warehouseenum.InventoryConditionGood, warehouseenum.InventoryConditionPackagingDamagedMinor, warehouseenum.InventoryConditionPackagingDamagedMajor, warehouseenum.InventoryConditionProductDamaged, warehouseenum.InventoryConditionOpened, warehouseenum.InventoryConditionContaminated, warehouseenum.InventoryConditionSpoiled}, invalid: warehouseenum.InventoryCondition("__invalid__")},
		{name: "warehouseenum.InventoryDisposition", valid: []stringEnum{warehouseenum.InventoryDispositionStandardSellable, warehouseenum.InventoryDispositionReducedSellable, warehouseenum.InventoryDispositionQualityHold, warehouseenum.InventoryDispositionQuarantined, warehouseenum.InventoryDispositionBlocked, warehouseenum.InventoryDispositionRecalled, warehouseenum.InventoryDispositionReturnToVendor, warehouseenum.InventoryDispositionScrap}, invalid: warehouseenum.InventoryDisposition("__invalid__")},
		{name: "warehouseenum.StockReservationStatus", valid: []stringEnum{warehouseenum.StockReservationStatusReserved, warehouseenum.StockReservationStatusPartiallyStaged, warehouseenum.StockReservationStatusStaged, warehouseenum.StockReservationStatusCommitted, warehouseenum.StockReservationStatusReleased, warehouseenum.StockReservationStatusExpired, warehouseenum.StockReservationStatusCancelled}, invalid: warehouseenum.StockReservationStatus("__invalid__")},
		{name: "warehouseenum.StockAvailabilityDirection", valid: []stringEnum{warehouseenum.StockAvailabilityOutOfStock, warehouseenum.StockAvailabilityRestocked}, invalid: warehouseenum.StockAvailabilityDirection("__invalid__")},
		{name: "warehouseenum.InventoryDateMarkThreshold", valid: []stringEnum{warehouseenum.InventoryDateMarkThresholdApproaching, warehouseenum.InventoryDateMarkThresholdReached, warehouseenum.InventoryDateMarkThresholdPassed}, invalid: warehouseenum.InventoryDateMarkThreshold("__invalid__")},
		{name: "warehouseenum.StockLocationPurpose", valid: []stringEnum{warehouseenum.StockLocationPurposeStandard, warehouseenum.StockLocationPurposeQualityHold, warehouseenum.StockLocationPurposeOnlineOrderStaging}, invalid: warehouseenum.StockLocationPurpose("__invalid__")},
		{name: "warehouseenum.StockLocationHandlingMode", valid: []stringEnum{warehouseenum.StockLocationHandlingEach, warehouseenum.StockLocationHandlingCase, warehouseenum.StockLocationHandlingMixed}, invalid: warehouseenum.StockLocationHandlingMode("__invalid__")},
		{name: "warehouseenum.StockLocationAccess", valid: []stringEnum{warehouseenum.StockLocationAccessCustomerAccessible, warehouseenum.StockLocationAccessStaffOnly}, invalid: warehouseenum.StockLocationAccess("__invalid__")},
		{name: "warehouseenum.StockLocationCollectionMode", valid: []stringEnum{warehouseenum.StockLocationCollectionAllowList, warehouseenum.StockLocationCollectionUnrestricted}, invalid: warehouseenum.StockLocationCollectionMode("__invalid__")},
		{name: "warehouseenum.StockLocationCollectionRole", valid: []stringEnum{warehouseenum.StockLocationCollectionPrimary, warehouseenum.StockLocationCollectionOverflow}, invalid: warehouseenum.StockLocationCollectionRole("__invalid__")},
		{name: "warehouseenum.StorageType", valid: []stringEnum{warehouseenum.StorageDry, warehouseenum.StorageChilled, warehouseenum.StorageFrozen}, invalid: warehouseenum.StorageType("__invalid__")},
		{name: "warehouseenum.WMSDraftStatus", valid: []stringEnum{warehouseenum.WMSDraftStatusDraft, warehouseenum.WMSDraftStatusSubmitted, warehouseenum.WMSDraftStatusCancelled}, invalid: warehouseenum.WMSDraftStatus("__invalid__")},
		{name: "warehouseenum.WMSDraftType", valid: []stringEnum{warehouseenum.WMSDraftTypeInbound, warehouseenum.WMSDraftTypeOutbound}, invalid: warehouseenum.WMSDraftType("__invalid__")},
	})
}
